feat: adding gitguardian precommit hook
isomerpages/isomercms-frontend pull request #1190
Opened 2023-03-02 06:22 UTC by harishv7

## Problem

While we do have checks post-commit to identify any secrets are committed, we should also attempt to prevent this even before a commit can occur.

After considering some solutions - https://github.com/awslabs/git-secrets and Git Guardian, we decided to go with GitGuardian since we are already using it.

## Solution

We add Git Guardian as a pre-commit hook which scans commits for any leaked secrets before actually performing the commit.

**Breaking Changes**

There is a breaking change for local development since this commit makes Git Guardian setup somewhat mandatory.

- [x] Yes - this PR contains breaking changes
  - Details ...
- [ ] No - this PR is backwards compatible

**New dev dependencies**:

No new dependencies are added to our package. Git Guardian will be installed on the OS-level instead as a brew package.

2023-03-07 03:01 UTC, seaerchin approved these changes
lgtm; can i just check if we've added the env var into our 1pw?

2023-03-07 03:11 UTC, kishore03109 requested changes
~~Chore: Opps I just realised this - we have a 'prepare' command in package.json. I think we should include `brew install gitguardian/tap/ggshield` inside that! (note this change would also be replicated in our backend code)~~

aye opps I thought the commands in `prepare` were done at the os level, but its not!

2023-03-07 06:25 UTC, kishore03109 approved these changes

2023-03-13 02:56 UTC, harishv7 commented
> lgtm; can i just check if we've added the env var into our 1pw?

Yea, @kishore03109 added it

2023-03-13 04:07 UTC, merged