chore(hero): duplicate template changes
isomerpages/isomercms-frontend pull request #1547
Opened 2023-10-02 04:50 UTC by seaerchin

## Problem
Duplicate of template [PR](https://github.com/isomerpages/isomerpages-template/pull/325) to frontend.

## Solution
1. change representation of `width` from `x%` to `sm/md` to allow for styles injection using css classes
2. new style for `floating` variant for 769 - 1023
3. side variant new design on super big width 
4. misc style changes

2023-10-02 08:38 UTC, dcshzj approved these changes

2023-10-03 01:51 UTC, alexanderleegs requested changes
Build is failing because of `@use 'templates/components/hero.scss';` in `isomer-template.scss` and `./src/styles/isomer-cms/pages/Editor.module.scss`

2023-10-03 02:51 UTC, seaerchin commented
@alexanderleegs - downstream PR [here](https://github.com/isomerpages/isomercms-frontend/pull/1548) fixes

2023-10-03 03:10 UTC, alexanderleegs approved these changes
oops forgot i alr reviewed the downstream

2023-10-03 03:36 UTC, merged