Fix/unstack image upload modal
isomerpages/isomercms-frontend pull request #169
Opened 2020-10-20 08:49 UTC by kwajiehao

## Overview

This PR resolves a litany of UI issues:
- #161: Shift `Heading` button in markdown editor to the front of the toolbar
- #163: Unstack media modals so that there is only one modal open at a time
- #164: Reposition action buttons (save or delete actions) to the bottom right hand corner
- Refactor to subsume the `EditResourcePage` component into `EditPage` since there is a lot of duplicated code

## Screenshots

2020-10-22 08:37 UTC, alexanderleegs requested changes
Left a minor comment.

Also currently, if the user is in the image upload modal but changes his mind, the entire modal is closed - we could possibly bring up the image select modal again, any thoughts on this? I'm open to leaving it as is also.

2020-10-22 08:37 UTC, alexanderleegs commented on src/layouts/EditPage.jsx
> +         * imgReader returns  `data:application/pdf;base64, {fileContent}`
nit: fileReader

2020-10-26 07:29 UTC, kwajiehao commented on src/layouts/EditPage.jsx
> +    const fileName = event.target.files[0].name;
test

2020-10-26 07:29 UTC, kwajiehao commented on src/layouts/EditPage.jsx
> +    const fileName = event.target.files[0].name;
test

2020-10-26 07:32 UTC, kwajiehao commented on src/layouts/EditPage.jsx
> +         * imgReader returns  `data:application/pdf;base64, {fileContent}`
fixed with [bc6bb97](https://github.com/isomerpages/isomercms-frontend/pull/169/commits/bc6bb97c5bb72f46bf54dd708301df63461f14ff)

2020-10-26 07:32 UTC, kwajiehao commented
> if the user is in the image upload modal but changes his mind, the entire modal is closed - we could possibly bring up the image select modal again, any thoughts on this? I'm open to leaving it as is also.

Re: this, I'm inclined to leave it as it is for now, and change it if the designers think it's a problem, since it's a pretty easy fix

2020-10-26 08:57 UTC, alexanderleegs approved these changes
lgtm

2020-10-26 09:22 UTC, merged