Feat/use site colors
isomerpages/isomercms-frontend pull request #296
Opened 2020-12-16 22:35 UTC by kwajiehao

## Overview

This PR resolves issue #149. It implements custom style sheets for each Isomer repo so that live previews resemble the actual web page even more. Refer to #149, specifically this comment ([link](https://github.com/isomerpages/isomercms-frontend/issues/149#issuecomment-718134200)), for more details on the rationale behind the implementation. This implements custom colors for the following layouts:
- `EditPage`
- `EditHomepage`
- `EditContactUs`

Samples:

**EditHomepage**
<img width="1680" alt="Screenshot 2020-12-17 at 6 19 23 AM" src="https://user-images.githubusercontent.com/31984694/102414165-00725480-4031-11eb-876a-967314aab806.png">

<img width="1678" alt="Screenshot 2020-12-17 at 6 25 42 AM" src="https://user-images.githubusercontent.com/31984694/102414198-0bc58000-4031-11eb-9c4b-dee1bc953b4f.png">

### Implementation

The implementation can be broken down into a few simple steps:
1. If color settings for the target repo already exist, skip this step. Otherwise, retrieve color settings from `_config.yml` file for the target repo. Extract the primary and secondary colors of the site
2. Create a custom style sheet when the `EditPage`/`EditHomepage`/`EditContactUs` layout mounts, and insert rules for specific HTML elements whose colors need to be modified.

### Notes on implementation

Ideally, I would have liked to use a React context to store the `siteColors` instead of a state hook at the App level. However, since the preview layouts (`EditPage`, `EditHomepage`, `EditContactUs`) are class components, we are not able to use the React Context API unless we refactor these class components into hooks, which would take significant engineering effort.

To mitigate this, I set up the code so that site colors are retrieved when one accesses the repo's `Workspace`. Any page navigated to from the `Workspace` will now have the site colors and will no longer need to retrieve them. However, if a user navigates directly to a preview layout (such as `EditPage`) and the site colors do not exist, then we will still retrieve them.

The downside to this approach is that because `siteColors` is passed as a prop to all layouts, when we update the `siteColors` hook, the page jumps and re-renders. This is something I'm not too happy about, and would welcome any technical solutions or workarounds which can prevent this re-render / jump.

2020-12-17 04:39 UTC, alexanderleegs requested changes
Code is clear and easy to understand, only have a minor nit.

Regarding the issue of the page re-renders, I was thinking we could possibly have an additional state variable to keep track of whether the colours have been loaded, and to prevent the page from loading until they have been retrieved?

2020-12-21 06:53 UTC, kwajiehao commented on src/utils/siteColorUtils.js
> +      if(sheet.title == unique_title) {
fixed with [b05671e](https://github.com/isomerpages/isomercms-frontend/pull/296/commits/b05671ed8f3288688b474c8fe427cc38d9df72a6)

2020-12-21 09:36 UTC, alexanderleegs approved these changes
lgtm. As discussed, we will leave the current re-rendering behaviour, as this can be fixed with context when the remaining class components are refactored.

2020-12-23 01:14 UTC, alexanderleegs requested changes
<img width="676" alt="Screenshot 2020-12-23 at 9 13 41 AM" src="https://user-images.githubusercontent.com/22111124/102947814-29965780-44ff-11eb-9099-c52e60a58f4b.png">
When the screen size is smaller the text isn't aligned consistently - could we standardise it to be center aligned for all?

2020-12-23 07:58 UTC, kwajiehao commented
> <img alt="Screenshot 2020-12-23 at 9 13 41 AM" width="676" src="https://user-images.githubusercontent.com/22111124/102947814-29965780-44ff-11eb-9099-c52e60a58f4b.png">
> 
> When the screen size is smaller the text isn't aligned consistently - could we standardise it to be center aligned for all?

Great catch, fixed in [9ea4b0f](https://github.com/isomerpages/isomercms-frontend/pull/296/commits/9ea4b0fa7843f12f6cbc646b9680b379711c3d34)

2020-12-23 08:39 UTC, alexanderleegs approved these changes
lgtm

2020-12-23 10:32 UTC, merged