Feat add resource category and fix create new folder
isomerpages/isomercms-frontend pull request #384
Opened 2021-03-23 03:41 UTC by alexanderleegs

This PR adds functionality for allowing empty folders, subfolders, and resource pages, as well as the associated changes required. To be reviewed in conjunction with PR #[137](https://github.com/isomerpages/isomercms-backend/pull/137) on the isomercms frontend repo. A discussion of the reasoning behind this change can be found [here](https://docs.google.com/document/d/1EccpS_ATrfOe4DmU4ChXtU9kV6Jl1rFOdKqBLyG6ym8/edit#).

The changes introduced in this PR are:

- Users can skip adding files to newly created folders/subfolders, allowing for the existence of empty folders
- The behaviour for handling empty subfolders and resource pages has been changed:
  - Previously, if it was detected that no pages were returned from the backend, we would automatically redirect them to the workspace/resources tab - this was to handle non-existent folders. However, since empty resource categories also return no files, this check has been moved to the backend, and categories that do not exist will throw an error, which is caught by the frontend and used to redirect users to the resources tab.
  - For subfolders, a new placeholder file has been added instead - we now check for this placeholder file to determine whether to redirect users. The placeholder files are also hidden from users.
-  To support the creation of new subfolders, an additional timeout has been added when creating folders. The reason for this is that the new collection.yml information takes time to propagate, and redirecting too soon retrieves the old data, which causes an immediate redirection to workspace. If anyone has a better fix for this, please let me know.
- `FolderNamingModal` has been fixed to allow for different field titles for the different types of folders.
- Misc bug fixes involving reorder page functionality, loading, and redirection bugs.
- Refactoring of Resources and partial refactoring of CategoryPages to use react-query - we will update CategoryPages in a future PR to only handle Resources.

2021-03-24 06:04 UTC, kwajiehao requested changes
Left a comment

2021-03-24 08:15 UTC, alexanderleegs commented on src/components/FolderCreationModal.jsx
> +        setTimeout(function() {
The issue with redirection doesn't seem to occur anymore - I'm not sure why it occurred in the first place. I've removed the timeout in https://github.com/isomerpages/isomercms-frontend/pull/384/commits/b867944dbe021154f4b43b98de0ac5a673ca4d0c

2021-03-24 08:16 UTC, alexanderleegs commented
> Left a comment
> 
> I also ran into a bug that occurred randomly. I didn't have problems creating empty subfolders, but when I attempted to create subfolders with some folder pages selected, I sometimes got this error on the backend: 
> 
> ```
> UnhandledPromiseRejectionWarning: ConflictError: A file with test/.keep already exists.
> ```
> 
> Although sometimes I got other errors:
> 
> ```
> "message":"is at f841fa5091c11a0fd2235657a957c04ff1fb2c85 but expected f47169b0706a0588cbaf49bb2a15e73aa1c33609","documentation_url":"https://docs.github.com/rest/reference/repos#delete-a-file"}},"isAxiosError":true,"name":"Error","message":"Request failed with status code 409"
> ```
> 
> To recreate this error:
> 
> 1. Go into a folder
> 2. Click on `Create new subfolder`
> 3. Select one or two pages to be added
> 4. Click `Done`

I think this error was related to not awaiting the creation of the subfolder in the backend, which caused the conflict - I haven't been able to reproduce the bug since then. Let me know if the issue persists!

2021-03-25 02:51 UTC, kwajiehao approved these changes
Lgtm, also nice fix for the loading button!

2021-03-25 05:18 UTC, merged