Fix/workspace folder pages ux
isomerpages/isomercms-frontend pull request #397
Opened 2021-04-06 08:18 UTC by gweiying

This PR fixes inconsistent behavior & layout on Workspace between the folders and the unlinked pages. Namely, these bugs are fixed:
- On hover, create button for both folders and pages turns blue
- Create button for pages changed from "Add a new page" to "Create new page" to match folders
- Create button for folders appears before ReactQuery completes. While query is running, loading message will appear. If no folders are retrieved, loading message will disappear. This behavior matches that of unlinked pages below.

2021-04-07 02:59 UTC, alexanderleegs requested changes
Left a comment

2021-04-07 02:59 UTC, alexanderleegs commented on src/layouts/Workspace.jsx
> +                  <FolderOptionButton title="Create new folder" option="create-sub" isSubfolder={false} onClick={() => setIsFolderCreationActive(true)}/>
Could we block this option from appearing until collections have been loaded? Otherwise an error occurs if users attempt to click it too early

2021-04-07 07:58 UTC, gweiying commented
We will let the designers review the different behaviours on staging and decide how to reconcile between them after they've looked at it!

2021-06-07 06:34 UTC, gweiying commented
outdated

2021-06-07 06:34 UTC, closed without merging