style: introduce aliasing, sort imports
isomerpages/isomercms-frontend pull request #511
Opened 2021-06-08 07:24 UTC by kwajiehao

# Overview

This PR is the frontend equivalent of PR #[194](https://github.com/isomerpages/isomercms-backend/pull/194) in the backend.  Broadly speaking, we wish to introduce aliases for our import paths, and to sort these imports. 

However, since the frontend uses Create React App (with its own configurations behind the scenes), it was not as straightforward as compared to the backend.

This PR makes the following changes:

### Other changes made
- Remove unused tree-related files (`tree-builder`, `tree-utils`) and packages (`@atlaskit/tree`)
- Use `prettier` instead of `plugin:prettier/recommended`. See backend PR #[195](https://github.com/isomerpages/isomercms-backend/pull/195) for more details
-

2021-06-09 04:13 UTC, prestonlimlianjie requested changes
lgtm apart from one small issue where Images and Folders tests are being commented out. Is this intentional?

2021-06-09 04:28 UTC, kwajiehao commented on src/__tests__/RouteSelector.jsx
> +// jest.mock("@layouts/Images", () => {
I've uncommented out the tests and filed an issue for these failing Jest mocks #513

2021-06-09 04:35 UTC, prestonlimlianjie commented
There are also some styling differences - probably from style import issues.

### Commit `f58cf86` (current `style/aliases` branch)
Some elements are using System-UI font like the repo name (`e2e-test-repo`), text in the Cards (`Homepage`, `Navigation Bar` etc).

<img width="1552" alt="Screenshot 2021-06-09 at 12 30 26 PM" src="https://user-images.githubusercontent.com/19917616/121293730-b05cb680-c91e-11eb-90bd-3a94fd70fdc8.png">

### Commit `531e571` (current `develop` branch)
Elements are using Lato font
<img width="1552" alt="Screenshot 2021-06-09 at 12 31 40 PM" src="https://user-images.githubusercontent.com/19917616/121293737-b2bf1080-c91e-11eb-8691-37fab6076a3b.png">

2021-06-09 10:21 UTC, kwajiehao commented
> There are also some styling differences - probably from style import issues.
> 
> ### Commit `f58cf86` (current `style/aliases` branch)
> Some elements are using System-UI font like the repo name (`e2e-test-repo`), text in the Cards (`Homepage`, `Navigation Bar` etc).
> 
> <img alt="Screenshot 2021-06-09 at 12 30 26 PM" width="1552" src="https://user-images.githubusercontent.com/19917616/121293730-b05cb680-c91e-11eb-90bd-3a94fd70fdc8.png">
> 
> ### Commit `531e571` (current `develop` branch)
> Elements are using Lato font
> <img alt="Screenshot 2021-06-09 at 12 31 40 PM" width="1552" src="https://user-images.githubusercontent.com/19917616/121293737-b2bf1080-c91e-11eb-8691-37fab6076a3b.png">

Fixed with [6682d98](https://github.com/isomerpages/isomercms-frontend/pull/511/commits/6682d982f61e51b456863a8e4ead1efa053cfcd2) - read the commit message for more details

2021-06-11 03:19 UTC, prestonlimlianjie approved these changes
lgtm!

2021-06-11 03:22 UTC, merged